name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test_build:
    runs-on: ubuntu-latest
    environment: Test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm install

      - name: Build Assets
        run: npm run build

      # - name: Copy Environment File
      #   run: cp .env.example .env

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Test ENV vars
        run: |
          echo "DB_STRING=$DB_STRING" >> .env
          echo "DB_NAME=$DB_NAME" >> .env
          echo "DB_USER=$DB_USER" >> .env
          echo "DB_PASS=$DB_PASS" >> .env
          echo "PORT=3000" >> .env

      - name: Tests
        env:
          PORT: 3000
          DB_STRING: $DB_STRING
          DB_NAME: $DB_NAME
          DB_USER: $DB_USER
          DB_PASS: $DB_PASS
        run: npm run test